"""add_generated_updates_to_documentation_update

Revision ID: a8c5984ee9bd
Revises: 7131f776166f
Create Date: 2026-02-22 16:38:39.160302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c5984ee9bd'
down_revision = '7131f776166f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation_updates', sa.Column('generated_updates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation_updates', 'generated_updates')
    # ### end Alembic commands ###
